import { useEffect, useRef, useState } from 'react';
import { CheckCircle2, FileText, LoaderCircle, RefreshCw, Upload, XCircle } from 'lucide-react';
import { documentApi } from '../../services/api';
import type { DocumentRecord, DocumentType } from '../../types';

const DOCUMENTS: Array<{ type: DocumentType; title: string }> = [
  { type: 'PAN_CARD', title: 'PAN Card' }, { type: 'AADHAAR_CARD', title: 'Aadhaar Card' }, { type: 'SALARY_SLIP', title: 'Salary Slip' },
  { type: 'BANK_STATEMENT', title: 'Bank Statement' }, { type: 'ADDRESS_PROOF', title: 'Address Proof' }, { type: 'EMPLOYMENT_INCOME_PROOF', title: 'Employment / Income Proof' },
];
const MAX_SIZE = 10 * 1024 * 1024;
const statusStyle = (status?: string) => status === 'VERIFIED' ? 'bg-green-100 text-green-700' : status === 'NEEDS_REVIEW' ? 'bg-amber-100 text-amber-800' : status === 'FAILED' ? 'bg-red-100 text-red-700' : status === 'VERIFYING' ? 'bg-blue-100 text-blue-700' : 'bg-slate-100 text-slate-600';
const statusLabel = (status?: string) => status ? status.replace('_', ' ').replace(/\b\w/g, c => c.toUpperCase()) : 'Not Uploaded';

export default function DocumentVerificationSection() {
  const [documents, setDocuments] = useState<Record<string, DocumentRecord>>({}); const [uploading, setUploading] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const inputRefs = useRef<Record<string, HTMLInputElement | null>>({});
  useEffect(() => { documentApi.pending().then(docs => setDocuments(Object.fromEntries(docs.map(d => [d.documentType, d])))).catch(() => setError('Could not load saved document statuses.')); }, []);
  const upload = async (type: DocumentType, file?: File) => { if (!file) { setError('Please select a document.'); return; } const title = DOCUMENTS.find(d => d.type === type)?.title ?? type; if (!window.confirm(`I confirm this file is my ${title}.`)) return; setError(null); if (!['application/pdf', 'image/jpeg', 'image/png'].includes(file.type)) { setError('Only PDF, JPG, JPEG, and PNG files are supported.'); return; } if (file.size > MAX_SIZE) { setError('File size exceeds the allowed 10 MB limit.'); return; } setUploading(type); try { const document = await documentApi.upload(type, file, true); setDocuments(prev => ({ ...prev, [type]: document })); } catch (err: unknown) { const data = (err as { response?: { data?: { message?: string; error?: string } } }).response?.data; setError(data?.message ?? data?.error ?? 'Upload failed. Please try again.'); } finally { setUploading(null); if (inputRefs.current[type]) inputRefs.current[type]!.value = ''; } };
  return <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div><p className="text-sm font-medium text-sky-700">Step 3 & 4</p><h2 className="text-lg font-semibold text-slate-800">Document Verification</h2><p className="mt-1 text-sm text-slate-500">Upload PDF, JPG or PNG files (up to 10 MB). AI-assisted checks are consistency checks, not government document authentication.</p></div>{error && <p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-5 grid gap-4 md:grid-cols-2">{DOCUMENTS.map(({ type, title }) => { const document = documents[type]; const status = uploading === type ? 'VERIFYING' : document?.status; const verification = document?.verification; return <article key={type} className="rounded-lg border border-slate-200 p-4 transition hover:border-sky-300"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-2 text-slate-800"><FileText size={18} className="text-[#0d3b70]"/><h3 className="font-semibold">{title}</h3></div><span className={`rounded-full px-2 py-1 text-xs font-semibold ${statusStyle(status)}`}>{uploading === type && <LoaderCircle className="mr-1 inline animate-spin" size={12}/>} {statusLabel(status)}</span></div><p className="mt-3 truncate text-xs text-slate-500">{document?.filename ?? 'No document selected'}</p>{verification && <p className="mt-2 text-xs text-slate-600">{verification.verificationMessage} Confidence: {Math.round(verification.confidence * 100)}%.</p>}<input ref={node => { inputRefs.current[type] = node; }} className="sr-only" id={`upload-${type}`} type="file" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" onChange={e => upload(type, e.target.files?.[0])} /><button type="button" disabled={uploading === type} onClick={() => inputRefs.current[type]?.click()} className="mt-4 inline-flex items-center gap-2 rounded-md border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50 disabled:opacity-60">{document ? <RefreshCw size={15}/> : <Upload size={15}/>} {document ? 'Replace document' : 'Upload document'}</button>{verification?.status === 'VERIFIED' && <CheckCircle2 className="float-right mt-5 text-green-600" size={18}/>} {verification?.status === 'NEEDS_REVIEW' && <XCircle className="float-right mt-5 text-amber-600" size={18}/>}</article>; })}</div></section>;
}
