"""initial schema

Revision ID: ae113030d130
Revises:
Create Date: 2026-08-13 20:19:12.102962

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "ae113030d130"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_users_email"), ["email"], unique=True
        )

    op.create_table(
        "applicants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("applicants", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_applicants_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "applications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("applicant_id", sa.Integer(), nullable=False),
        sa.Column("features_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["applicant_id"],
            ["applicants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_applications_applicant_id"),
            ["applicant_id"],
            unique=False,
        )

    op.create_table(
        "predictions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("model_name", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("predictions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_predictions_application_id"),
            ["application_id"],
            unique=True,
        )

    op.create_table(
        "counterfactuals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prediction_id", sa.Integer(), nullable=False),
        sa.Column("found", sa.Boolean(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("alternatives_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["predictions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("counterfactuals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_counterfactuals_prediction_id"),
            ["prediction_id"],
            unique=False,
        )

    op.create_table(
        "explanations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prediction_id", sa.Integer(), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("contributions_json", sa.Text(), nullable=False),
        sa.Column("plain_english", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["predictions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "prediction_id", "method", name="uq_prediction_method"
        ),
    )
    with op.batch_alter_table("explanations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_explanations_prediction_id"),
            ["prediction_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("explanations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_explanations_prediction_id"))

    op.drop_table("explanations")
    with op.batch_alter_table("counterfactuals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_counterfactuals_prediction_id"))

    op.drop_table("counterfactuals")
    with op.batch_alter_table("predictions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_predictions_application_id"))

    op.drop_table("predictions")
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_applications_applicant_id"))

    op.drop_table("applications")
    with op.batch_alter_table("applicants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_applicants_user_id"))

    op.drop_table("applicants")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
