import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ExternalLink } from 'lucide-react';
import { documentApi } from '../../services/api';
import type { DocumentRecord } from '../../types';

type Row = DocumentRecord & { applicant?: { full_name: string; email: string } };
export default function DocumentVerification() {
  const [documents, setDocuments] = useState<Row[]>([]); const [selected, setSelected] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const load = () => documentApi.pending().then(setDocuments).catch(e => setError(e?.response?.data?.error ?? 'Could not load document verification records.'));
  useEffect(() => { load(); }, []);
  const groups = useMemo(() => Object.values(documents.reduce<Record<string, { name: string; email: string; docs: Row[] }>>((all, doc) => { const key = doc.applicant?.email ?? 'unknown'; (all[key] ??= { name: doc.applicant?.full_name ?? 'Applicant', email: key, docs: [] }).docs.push(doc); return all; }, {})), [documents]);
  const applicant = groups.find(g => g.email === selected); const review = async (id: number, documentStatus: 'approved' | 'rejected') => { await documentApi.review(id, documentStatus); load(); };
  if (applicant) return <div className="space-y-6"><button onClick={() => setSelected(null)} className="inline-flex items-center gap-2 text-sm font-semibold text-brand-700"><ArrowLeft size={16}/> All applicants</button><h1 className="text-3xl font-bold text-slate-900">{applicant.name}'s documents</h1><div className="grid gap-4 md:grid-cols-2">{applicant.docs.map(doc => <article key={doc.id} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-800">{doc.documentType.replaceAll('_', ' ')}</h2><p className="mt-1 text-sm text-slate-500">{doc.filename}</p><p className="mt-3 text-sm text-slate-600">{doc.verification?.verificationMessage ?? 'Awaiting automated check.'}</p><a className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-brand-700" target="_blank" rel="noreferrer" href={documentApi.fileUrl(doc.id)}><ExternalLink size={15}/> Preview</a><div className="mt-4 flex gap-2"><button onClick={() => review(doc.id, 'approved')} className="rounded-md bg-emerald-600 px-3 py-2 text-sm font-semibold text-white">Approve</button><button onClick={() => review(doc.id, 'rejected')} className="rounded-md bg-red-600 px-3 py-2 text-sm font-semibold text-white">Reject</button></div><p className="mt-3 text-xs capitalize text-slate-500">Human review: {doc.documentStatus ?? 'pending'}</p></article>)}</div></div>;
  return <div className="space-y-6"><div><p className="eyebrow">Admin / Verification</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Document verification</h1><p className="mt-2 text-slate-500">Select an applicant to review every submitted document.</p></div>{error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="grid gap-4 md:grid-cols-2">{groups.map(group => <button key={group.email} onClick={() => setSelected(group.email)} className="rounded-xl border border-slate-200 bg-white p-5 text-left shadow-sm hover:border-brand-400"><h2 className="font-semibold text-slate-900">{group.name}</h2><p className="mt-1 text-sm text-slate-500">{group.email}</p><p className="mt-4 text-sm text-slate-600">{group.docs.length} documents submitted · {group.docs.every(d => d.documentStatus === 'approved') ? 'Approved' : 'Pending review'}</p></button>)}</div>{!groups.length && <p className="rounded-xl border border-dashed p-8 text-center text-sm text-slate-500">No submitted documents require review.</p>}</div>;
}
