import { useEffect, useState } from 'react';
import { documentApi } from '../../services/api';
import type { DocumentRecord } from '../../types';

export default function DocumentVerification() {
  const [documents, setDocuments] = useState<Array<DocumentRecord & { applicant?: { full_name: string; email: string } }>>([]);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { documentApi.pending().then(setDocuments).catch((requestError) => setError(requestError?.response?.data?.error ?? 'Could not load document verification records.')); }, []);
  return <div className="space-y-6"><div><p className="eyebrow">Admin / Verification</p><h1 className="mt-1 text-3xl font-bold text-[#102a4c]">Document verification</h1><p className="mt-2 text-slate-500">Review simulated consistency checks attached to applicant submissions.</p></div>{error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-4">Applicant</th><th className="p-4">Document</th><th className="p-4">Status</th><th className="p-4">Mismatches</th><th className="p-4">Checked</th></tr></thead><tbody>{documents.map((document) => <tr key={document.id} className="border-b border-slate-100 last:border-0"><td className="p-4"><p className="font-medium text-slate-700">{document.applicant?.full_name ?? 'Applicant'}</p><p className="text-xs text-slate-500">{document.applicant?.email}</p></td><td className="p-4 text-slate-600">{document.documentType}</td><td className="p-4"><span className={document.verification?.status === 'VERIFIED' ? 'text-green-700' : 'text-amber-700'}>{document.verification?.status ?? document.status}</span></td><td className="p-4 text-slate-600">{document.verification?.mismatches?.length ?? 0}</td><td className="p-4 text-slate-500">{document.verification?.verifiedAt ? new Date(document.verification.verifiedAt).toLocaleString() : 'Pending'}</td></tr>)}</tbody></table>{documents.length === 0 && <p className="p-8 text-center text-sm text-slate-500">No submitted documents require review.</p>}</div></div>;
}
