import { useEffect, useState } from 'react';
import { isAxiosError } from 'axios';
import { adminApi, type AdminReviewApplication } from '../../services/api';
import { StatusBadge } from '../../components/common/StatusBadge';

export default function ReviewQueue() {
  const [reviews, setReviews] = useState<AdminReviewApplication[]>([]);
  const [expanded, setExpanded] = useState<number | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState<number | null>(null);
  useEffect(() => { adminApi.pendingReviews().then(setReviews).catch((requestError) => setError(requestError?.response?.data?.error ?? 'Could not load the review queue.')); }, []);
  const decide = async (id: number, decision: 'APPROVE' | 'REJECT') => {
    setBusy(id); setError(null);
    try { await adminApi.decideReview(id, decision); setReviews((items) => items.filter((item) => item.id !== id)); }
    catch (requestError) { setError(isAxiosError(requestError) ? requestError.response?.data?.error ?? 'Could not save the decision.' : 'Could not save the decision.'); }
    finally { setBusy(null); }
  };
  return <div className="space-y-6"><div><p className="eyebrow">Admin / Review Queue</p><h1 className="mt-1 text-3xl font-bold text-[#102a4c]">Manual review queue</h1><p className="mt-2 text-slate-500">Every item below is a model REVIEW decision awaiting an auditable final decision.</p></div>{error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{reviews.length === 0 ? <div className="rounded-xl border border-slate-200 bg-white p-8 text-center text-sm text-slate-500">No applications are awaiting review.</div> : <div className="space-y-3">{reviews.map((review) => { const isOpen = expanded === review.id; return <article key={review.id} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{review.application_id}</p><h2 className="mt-1 text-lg font-semibold text-slate-800">{review.applicant.full_name}</h2><p className="text-sm text-slate-500">{review.applicant.email}</p><div className="mt-3 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-amber-50 px-2 py-1 font-semibold text-amber-800">REVIEW</span><span className="rounded-full bg-slate-100 px-2 py-1 text-slate-600">Risk score {review.prediction?.risk_score ?? '—'} / 100</span><StatusBadge value={review.prediction?.risk_level ?? 'MEDIUM'} /></div></div><div className="flex gap-2"><button type="button" disabled={busy === review.id} onClick={() => decide(review.id, 'APPROVE')} className="rounded-md bg-green-700 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50">Approve</button><button type="button" disabled={busy === review.id} onClick={() => decide(review.id, 'REJECT')} className="rounded-md bg-red-700 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50">Reject</button></div></div><button type="button" onClick={() => setExpanded(isOpen ? null : review.id)} className="mt-4 text-sm font-medium text-brand-700 hover:underline">{isOpen ? 'Hide explanation' : 'View SHAP, LIME and counterfactual'}</button>{isOpen && <div className="mt-4 grid gap-4 border-t border-slate-100 pt-4 md:grid-cols-3"><div><h3 className="text-sm font-semibold text-slate-700">SHAP</h3><p className="mt-1 text-sm text-slate-600">{review.shap?.plain_english ?? 'No stored SHAP explanation.'}</p></div><div><h3 className="text-sm font-semibold text-slate-700">LIME</h3><p className="mt-1 text-sm text-slate-600">{review.lime?.plain_english ?? 'No stored LIME explanation.'}</p></div><div><h3 className="text-sm font-semibold text-slate-700">DiCE counterfactual</h3><p className="mt-1 text-sm text-slate-600">{review.counterfactual?.message ?? 'No counterfactual was generated.'}</p></div></div>}</article>; })}</div>}</div>;
}
